#version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: herick
      POSTGRES_PASSWORD: test
      POSTGRES_DB: toDoBase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U herick"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: